name: Generate Sitemaps for All Clients

on:
  push:
    branches: [ main ]
    paths:
      - '**/markdown/**'  # Déclenche si un fichier dans n'importe quel dossier markdown/ est modifié

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Récupère tout l'historique pour éviter les conflits

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install markdown

      - name: Generate sitemaps
        run: |
          python generate_sitemap.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          # Vérifie s'il y a des changements avant de commiter
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-generate sitemaps for all clients"
            git push
          else
            echo "No changes to commit"
          fi
